const AppActions = {
  LOGOUT: 'Auth_Logout',
  LOGOUT_SUCCESS: 'Auth_Logout_Success',
  LOGIN: 'Auth_Login',
  LOGIN_SUCCESS: 'Auth_Login_Success',
  LOGIN_FAIL: 'Auth_Login_Fail',
  IGNORE_LOGIN: 'Ignore_Login',
  REQUEST_OTP: 'Request_OTP',
  REQUEST_OTP_SUCCESS: 'Request_OTP_Success',
  REQUEST_OTP_FAIL: 'Request_OTP_Fail',
  IS_LOCK: 'Is_Locked',
  EXIT_APP: 'Exit',
  APP_STARTED: 'App_Stared',
  APP_START_FAILED: 'App_Start_Failed',
  LOADED: 'Loaded',
  GOTO_OTP_SCREEN: '@GOTO/OTP_Screen',
  NOTIFIES_GET_REQUEST: 'Notifies/get_request',
  NOTIFIES_GET_SUCCESS: 'Notifies/get_success',
  NOTIFIES_GET_FAIL: 'Notifies/get_fail',
  CART_SELECT_ITEM: 'Cart/Select_Item',
  CART_ADD_ITEM: 'Cart/Add_Item',
  CART_UPDATE_PAYMENT: 'Cart/Update_Payment',
  CART_UPDATE_INFO: 'Cart/Update_Info',
  CART_UPDATE_TIME: 'Cart/Update_Time',
  CART_UPDATE_COUPON: 'Cart/Update_Coupon',
  CART_UPDATE_NOTE: 'Cart/Update_Note',
  CART_RENEW: 'Cart/Renew',
  USER_INFO_UPDATE: 'UserInfo/update',
};

export default AppActions;
