require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

# Override Firebase SDK Version
$FirebaseSDKVersion = '6.13.0'

# Override Fabric SDK Version
$FabricSDKVersion = '1.6.0'

# Override Crashlytics SDK Version
$CrashlyticsSDKVersion = '3.1.0'

$RNFirebaseAsStaticFramework = true

target 'XanhCoffee' do 
  # Pods for XanhCoffees
  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  config = use_native_modules!
  use_react_native!(:path => config["../node_modules/react-native"])

  pod 'react-native-text-input-mask', :path => '../node_modules/react-native-text-input-mask'

  target 'XanhCoffeeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'XanhCoffee-tvOS' do
  # Pods for XanhCoffee-tvOS

  target 'XanhCoffee-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
